"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, Clock3, MapPin, ShieldCheck, UserRound } from "lucide-react";
import { Portrait } from "@/components/profile/portrait";
import { Button } from "@/components/ui/button";

export function ShareDateFlow() {
  const [confirmed, setConfirmed] = useState(false); const [safe, setSafe] = useState(false);
  const [form, setForm] = useState({ venue: "Patan Museum Café", date: "", contact: "", deadline: "21:30" });
  if (confirmed) return <main className="flex min-h-[calc(100dvh-84px)] flex-col px-5 pb-8 pt-[max(24px,env(safe-area-inset-top))]"><div className="mx-auto mt-12 grid size-20 place-items-center rounded-[28px] bg-success/12 text-success"><ShieldCheck size={34}/></div><h1 className="mt-7 text-center text-3xl font-semibold tracking-tight">Your date plan is ready.</h1><p className="mt-3 text-center text-sm leading-6 text-stone">This demo stores nothing and sends nothing. In production, delivery must happen through a secure trusted server.</p><div className="mt-7 rounded-[24px] border bg-surface p-5"><div className="flex items-center gap-3"><Portrait quadrant="tr" alt="Fictional match" className="size-12 rounded-full"/><div><p className="font-semibold">Rohan</p><p className="text-xs text-stone">{form.venue}</p></div></div><dl className="mt-5 grid gap-3 text-sm"><div className="flex justify-between"><dt className="text-stone">Check-in by</dt><dd className="font-medium">{form.deadline}</dd></div><div className="flex justify-between"><dt className="text-stone">Trusted contact</dt><dd className="font-medium">{form.contact || "Demo contact"}</dd></div></dl></div><div className="mt-auto"><Button onClick={() => setSafe(true)} disabled={safe} className="w-full bg-success from-success to-success">{safe ? <><Check/>Checked in safely</> : "I’m safe"}</Button><Link href="/safety" className="mt-3 flex h-12 items-center justify-center text-sm font-semibold text-stone">Back to Safety Center</Link></div></main>;
  return <main className="px-5 pb-8 pt-[max(20px,env(safe-area-inset-top))]"><div className="flex items-center gap-3"><Link href="/safety" className="grid size-11 place-items-center rounded-full border"><ArrowLeft size={19}/></Link><div><p className="text-xs font-bold tracking-[.14em] text-success">SHARE DATE</p><h1 className="text-2xl font-semibold">Make a private plan</h1></div></div><p className="mt-6 text-sm leading-6 text-stone">Share the essentials with someone you trust and choose when they should expect your check-in.</p>
  <div className="mt-6 space-y-4"><label className="block"><span className="text-sm font-semibold">Match</span><div className="mt-2 flex h-16 items-center gap-3 rounded-2xl border bg-surface px-4"><Portrait quadrant="tr" alt="Fictional match" className="size-10 rounded-full"/><span className="font-medium">Rohan</span><span className="ml-auto text-success">✓</span></div></label><Field icon={MapPin} label="Venue" value={form.venue} onChange={(value) => setForm({ ...form, venue: value })} placeholder="Public venue"/><Field icon={Clock3} label="Date & time" value={form.date} onChange={(value) => setForm({ ...form, date: value })} placeholder="Saturday, 4:00 PM"/><Field icon={UserRound} label="Trusted contact" value={form.contact} onChange={(value) => setForm({ ...form, contact: value })} placeholder="Name or phone number"/><Field icon={ShieldCheck} label="Check-in deadline" value={form.deadline} onChange={(value) => setForm({ ...form, deadline: value })} placeholder="9:30 PM"/></div><div className="mt-6 rounded-2xl bg-[#fff8e8] p-4 text-xs leading-5 text-[#6c4b0b] dark:bg-[#2a2111] dark:text-[#f5d78f]"><b>Prototype note:</b> This flow does not send information until a secure delivery service is configured.</div><Button onClick={() => setConfirmed(true)} className="mt-6 w-full">Confirm date plan</Button>
  </main>;
}
function Field({ icon: Icon, label, value, onChange, placeholder }: { icon: typeof MapPin; label: string; value: string; onChange: (value: string) => void; placeholder: string }) { return <label className="block"><span className="text-sm font-semibold">{label}</span><span className="mt-2 flex h-14 items-center gap-3 rounded-2xl border bg-surface px-4"><Icon size={18} className="text-stone"/><input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="min-w-0 flex-1 bg-transparent outline-none"/></span></label>; }
