"use client";

import { useState } from "react";
import { AlertTriangle, BarChart3, CheckCircle2, ChevronRight, CircleSlash2, Eye, Flag, ShieldCheck, Sparkles, Users } from "lucide-react";
import { Wordmark } from "@/components/brand/brand-mark";

const metrics = [
  { label: "Daily active", value: "2,418", delta: "+8.4%", icon: Users },
  { label: "Matches / day", value: "684", delta: "+5.1%", icon: Sparkles },
  { label: "Like → match", value: "18.7%", delta: "+1.2%", icon: BarChart3 },
  { label: "Report rate", value: "0.34%", delta: "−0.06%", icon: Flag },
  { label: "Verified", value: "71%", delta: "+3.8%", icon: ShieldCheck },
];
const reports = [
  { id: "R-2481", reason: "Impersonation", subject: "Profile f2…91", age: "12m", risk: "High" },
  { id: "R-2479", reason: "Harassment", subject: "Profile a1…08", age: "37m", risk: "High" },
  { id: "R-2471", reason: "Fake profile", subject: "Profile 8d…13", age: "2h", risk: "Medium" },
  { id: "R-2468", reason: "Scam", subject: "Profile 7b…24", age: "3h", risk: "Medium" },
];

export function AdminDashboard() {
  const [flags, setFlags] = useState({ waitlist: false, voicePrompts: false, photoReview: true, shareDate: true });
  const toggle = (key: keyof typeof flags) => setFlags((value) => ({ ...value, [key]: !value[key] }));
  return <main className="min-h-dvh bg-[#f4efec] text-[#171417] dark:bg-[#0d0c0e] dark:text-[#faf7f8]"><header className="border-b bg-surface"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Wordmark compact/><div className="flex items-center gap-3"><span className="rounded-full bg-[#fff0f2] px-3 py-2 text-xs font-semibold text-wine dark:bg-[#32141d] dark:text-[#ff9aac]">Development guard</span><div className="grid size-10 place-items-center rounded-full bg-ink text-xs font-bold text-ivory">AM</div></div></div></header>
  <div className="mx-auto grid max-w-7xl gap-6 px-5 py-8 lg:grid-cols-[1fr_320px] lg:px-8"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-crimson">MODERATION OVERVIEW</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Keep the room kind.</h1><p className="mt-2 text-sm text-stone">Operational signals without arbitrary access to private message content.</p>
  <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(({ label, value, delta, icon: Icon }) => <article key={label} className="rounded-[20px] border bg-surface p-4"><Icon size={18} className="text-crimson"/><p className="mt-4 text-2xl font-semibold">{value}</p><div className="mt-1 flex justify-between gap-2 text-xs"><span className="text-stone">{label}</span><span className="font-semibold text-success">{delta}</span></div></article>)}</section>
  <section className="mt-6 overflow-hidden rounded-[24px] border bg-surface"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">Report moderation queue</h2><p className="mt-1 text-xs text-stone">Prioritized by harm signals and repeat history</p></div><span className="rounded-full bg-crimson/10 px-3 py-1 text-xs font-bold text-crimson">14 open</span></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-foreground/3 text-xs uppercase tracking-wide text-stone"><tr><th className="px-5 py-3">Report</th><th className="px-5 py-3">Reason</th><th className="px-5 py-3">Account</th><th className="px-5 py-3">Age</th><th className="px-5 py-3">Priority</th><th className="px-5 py-3"><span className="sr-only">Open</span></th></tr></thead><tbody className="divide-y">{reports.map((report) => <tr key={report.id}><td className="px-5 py-4 font-medium">{report.id}</td><td className="px-5 py-4">{report.reason}</td><td className="px-5 py-4 font-mono text-xs text-stone">{report.subject}</td><td className="px-5 py-4 text-stone">{report.age}</td><td className="px-5 py-4"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${report.risk === "High" ? "bg-crimson/10 text-crimson" : "bg-[#fff4d6] text-[#795a00]"}`}>{report.risk}</span></td><td className="px-5 py-4"><button className="grid size-9 place-items-center rounded-full border" aria-label={`Open ${report.id}`}><ChevronRight size={16}/></button></td></tr>)}</tbody></table></div><div className="border-t bg-foreground/2 px-5 py-3 text-xs text-stone"><Eye size={14} className="mr-2 inline"/>Message metadata only. Content access requires a future explicit abuse-review authorization flow.</div></section>
  <section className="mt-6 grid gap-4 md:grid-cols-3"><AdminMini title="User moderation" value="9 restricted" icon={CircleSlash2}/><AdminMini title="Verification requests" value="32 pending" icon={CheckCircle2}/><AdminMini title="Banned accounts" value="184 total" icon={AlertTriangle}/></section></div>
  <aside className="space-y-6"><section className="rounded-[24px] border bg-surface p-5"><h2 className="font-semibold">Feature flags</h2><p className="mt-1 text-xs leading-5 text-stone">Server-authoritative in production.</p><div className="mt-4 divide-y">{Object.entries(flags).map(([key, value]) => <button key={key} role="switch" aria-checked={value} onClick={() => toggle(key as keyof typeof flags)} className="flex min-h-14 w-full items-center justify-between gap-3 text-left"><span className="text-sm font-medium capitalize">{key.replace(/([A-Z])/g, " $1")}</span><span className={`relative h-6 w-11 rounded-full ${value ? "bg-crimson" : "bg-foreground/15"}`}><span className={`absolute top-1 size-4 rounded-full bg-white transition ${value ? "left-6" : "left-1"}`}/></span></button>)}</div></section><section className="rounded-[24px] bg-[#1d1619] p-5 text-white"><ShieldCheck className="text-[#ff7188]"/><h2 className="mt-4 font-semibold">Role boundary</h2><p className="mt-2 text-xs leading-5 text-white/60">This demo guard is development-only. Production admin access must come from a trusted server role or signed claim—not client state.</p></section></aside></div></main>;
}
function AdminMini({ title, value, icon: Icon }: { title: string; value: string; icon: typeof Users }) { return <article className="flex items-center gap-4 rounded-[20px] border bg-surface p-4"><span className="grid size-11 place-items-center rounded-2xl bg-foreground/5 text-stone"><Icon size={19}/></span><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-stone">{value}</p></div></article>; }
