import Link from "next/link";
import { ArrowUpRight, MessageCircle } from "lucide-react";
import { Portrait } from "@/components/profile/portrait";
import { conversations, getProfile, profiles } from "@/data/profiles";

export default function ChatsPage() {
  return <main className="pb-6 pt-[max(26px,env(safe-area-inset-top))]"><div className="px-5"><p className="text-xs font-bold tracking-[.14em] text-crimson">CONVERSATIONS</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.05em]">Chats</h1><p className="mt-2 text-sm text-stone">The good part starts after the match.</p></div>
    <section className="mt-7"><div className="flex items-center justify-between px-5"><h2 className="text-sm font-semibold">Recent matches</h2><span className="text-xs text-stone">Say hello</span></div><div className="hide-scrollbar mt-3 flex gap-4 overflow-x-auto px-5 pb-2">{profiles.slice(0,5).map((profile) => <Link key={profile.id} href={`/chats/${profile.id}`} className="w-16 shrink-0 text-center"><div className="relative"><Portrait quadrant={profile.portrait} alt={`Fictional portrait of ${profile.firstName}`} className="mx-auto size-15 rounded-full"/><span className="absolute bottom-0 right-0 size-4 rounded-full border-[3px] border-background bg-success"/></div><span className="mt-2 block truncate text-xs font-medium">{profile.firstName}</span></Link>)}</div></section>
    <section className="mt-7 px-3"><h2 className="px-2 text-sm font-semibold">Messages</h2><div className="mt-2 divide-y">{conversations.map((conversation) => { const profile = getProfile(conversation.profileId)!; return <Link key={conversation.id} href={`/chats/${conversation.id}`} className="flex min-h-[86px] items-center gap-3 rounded-2xl px-2 transition hover:bg-foreground/4"><Portrait quadrant={profile.portrait} alt={`Fictional portrait of ${profile.firstName}`} className="size-14 shrink-0 rounded-full"/><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="font-semibold">{profile.firstName}{profile.verified && <span className="ml-1 text-success">✓</span>}</p><span className="text-[11px] text-stone">{conversation.timestamp}</span></div><p className={`mt-1 truncate text-sm ${conversation.unread ? "font-medium text-foreground" : "text-stone"}`}>{conversation.lastMessage}</p></div>{conversation.unread ? <span className="grid size-6 place-items-center rounded-full bg-crimson text-[11px] font-bold text-white">{conversation.unread}</span> : <ArrowUpRight size={16} className="text-stone"/>}</Link>; })}</div></section>
    {conversations.length === 0 && <div className="mx-5 mt-12 rounded-[28px] border p-8 text-center"><MessageCircle className="mx-auto text-crimson"/><h2 className="mt-4 text-xl font-semibold">Your next conversation hasn’t started yet.</h2><p className="mt-2 text-sm text-stone">A good prompt can make the first hello easier.</p></div>}
  </main>;
}
